### ISSUE TITLE
Реализуй паттерн липкого футера

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy-adaptive/2450769-cat-energy-31#61]
Современная реализация этого паттерна сильно упростила задачу. Теперь не нужно что-то делать с элементом `html`, всё настраивается у `body` (или у класса на нём) :
1. Задай минимальную высоту равную наименьшей (`s` от _small_) из возможных высот вьюпорта:
	```scss
	.page__body {
		min-height: 100svh;
	}
	```
2. Задай там же грид с автоматической (под контент) высотой ряда под `header`, и растягивающимся на всё доступное место рядом под `main` (другие ряды указывать не нужно, они будут `auto` по дефолту):
	```scss
	.page__body {
		min-height: 100svh;
		display: grid;
		grid-template-rows: auto 1fr;
	}
	```
	или если в логических свойствах/юнитах:
	```scss
	.page__body {
		min-block-size: 100svb;
		display: grid;
		grid-template-rows: auto 1fr;
	}
	```

Важно не обмануться кажущимся логичным использованием `dvh` (`dvb`): этот юнит в данном паттерне даёт очень неприятный эффект при начале скролла на мобильных браузерах, когда у них скрывается адресная/навигационная строка — весь интерфейс дёргается. `svh` работает как ожидается.
